name: flutter_dart_extension
description: If you find this Dart extension for customizing UI widgets helpful and time-saving, I kindly suggest considering its use in your projects. Should you feel it offers value to the Flutter community, you may wish to share it with others on platforms like GitHub, where fellow developers can support it by giving it stars. Your thoughtful consideration and potential contributions, including stars, would be greatly appreciated.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
